# Generated by Django 3.1 on 2020-08-20 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField( max_length=30)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE UNVERIFIED'), ('2', 'ACTIVE VERIFIED'), ('3', 'INACTIVE')], default='1', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('1', 'BANCO NACIONAL BOLIVIA'), ('2', 'TIGO MONEY')], max_length=50)),
                ('status', models.CharField(choices=[('1', 'ACTIVE UNVERIFIED'), ('2', 'ACTIVE VERIFIED'), ('3', 'INACTIVE')], default='1', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_timestamp', models.DateTimeField(auto_now=True)),
                ('actiontype', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('1', 'INCOMPLETE'), ('2', 'PENDING'), ('3', 'CANCELLED'), ('4', 'COMPLETE')], default='2', max_length=10)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
