# Generated by Django 3.1 on 2020-08-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20200820_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='DEFUALT EMAIL', max_length=50, unique=True),
        ),
    ]
