# Generated by Django 3.1 on 2020-08-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20200821_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_superuser',
            new_name='superuser',
        ),
    ]
